---
# tasks file for k8s-nodes

- name: Configure node ip
  lineinfile:
    create: true
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted    

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777
  become: true
 
- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  become: true
  

