---
# tasks file for k8s-nodes

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777
  become: true

 
- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  become: true
  

